### ISSUE TITLE
Altimeter data not being retrieved correctly

### ISSUE THREAD

**Issue by thomasfifer** [ESFT/launchpad#2]
I2CSlaveDataGet() returns 0 instead of data from altimeter

**Comment by thomasfifer** [comment]
changed I2CSlaveDataGet() to I2MasterDataGet() but now receiving 0xFF instead of 0

**Comment by santaryan** [comment]
When looking at the registers, I2C_MDR_DATA on I2C0 is not being set correctly.

Will continue to look into the problem.

**Comment by santaryan** [comment]
Altimeter Reset and CRC calculation now good.

Now hanging on reading ADC conversion data

**Comment by santaryan** [comment]
Burst read is failing to work for ADC conversion to get converted data

Sensor is not acknowledging

**Comment by santaryan** [comment]
Fixed the problem.
I was using the bitand operator between the base conversion command and the OSR+D1/D2 command resulting in a 0x0 being sent instead of the correct conversion command.
